/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppContainer: typeof import('./src/components/AppContainer/index.vue')['default']
    BindMobile: typeof import('./src/components/BindMobile/index.vue')['default']
    CapabilityShowcase: typeof import('./src/components/sections/CapabilityShowcase.vue')['default']
    ExperienceLab: typeof import('./src/components/sections/ExperienceLab.vue')['default']
    GradientFeature: typeof import('./src/components/sections/GradientFeature.vue')['default']
    HeroShowcase: typeof import('./src/components/sections/HeroShowcase.vue')['default']
    IconGallery: typeof import('./src/components/sections/IconGallery.vue')['default']
    MacroShowcase: typeof import('./src/components/sections/MacroShowcase.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutConfigProvider: typeof import('nutui-uniapp/components/configprovider/configprovider.vue')['default']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['default']
    NutTabPane: typeof import('nutui-uniapp/components/tabpane/tabpane.vue')['default']
    NutTabs: typeof import('nutui-uniapp/components/tabs/tabs.vue')['default']
    NutToast: typeof import('nutui-uniapp/components/toast/toast.vue')['default']
    WeappTailwindcss: typeof import('./src/components/WeappTailwindcss.vue')['default']
  }
}
