/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppContainer: typeof import('./src/components/AppContainer/index.vue')['default']
    BindMobile: typeof import('./src/components/BindMobile/index.vue')['default']
    CapabilityShowcase: typeof import('./src/components/sections/CapabilityShowcase.vue')['default']
    CarNumberInput: typeof import('./src/components/CarNumberInput/index.vue')['default']
    Empty: typeof import('./src/components/Empty/index.vue')['default']
    ExperienceLab: typeof import('./src/components/sections/ExperienceLab.vue')['default']
    GradientFeature: typeof import('./src/components/sections/GradientFeature.vue')['default']
    HeroShowcase: typeof import('./src/components/sections/HeroShowcase.vue')['default']
    IconGallery: typeof import('./src/components/sections/IconGallery.vue')['default']
    Loading: typeof import('./src/components/Loading/index.vue')['default']
    LoadingAnnulus: typeof import('./src/components/Loading/static/loading-annulus.vue')['default']
    LoadingAtom: typeof import('./src/components/Loading/static/loading-atom.vue')['default']
    LoadingBounce: typeof import('./src/components/Loading/static/loading-bounce.vue')['default']
    LoadingCircle: typeof import('./src/components/Loading/static/loading-circle.vue')['default']
    LoadingEqual: typeof import('./src/components/Loading/static/loading-equal.vue')['default']
    LoadingEyes: typeof import('./src/components/Loading/static/loading-eyes.vue')['default']
    LoadingGear: typeof import('./src/components/Loading/static/loading-gear.vue')['default']
    LoadingLove: typeof import('./src/components/Loading/static/loading-love.vue')['default']
    LoadingPulse: typeof import('./src/components/Loading/static/loading-pulse.vue')['default']
    LoadingRadar: typeof import('./src/components/Loading/static/loading-radar.vue')['default']
    LoadingSun: typeof import('./src/components/Loading/static/loading-sun.vue')['default']
    LoadingSurround: typeof import('./src/components/Loading/static/loading-surround.vue')['default']
    LoadingSword: typeof import('./src/components/Loading/static/loading-sword.vue')['default']
    LoadingWobble: typeof import('./src/components/Loading/static/loading-wobble.vue')['default']
    MacroShowcase: typeof import('./src/components/sections/MacroShowcase.vue')['default']
    MonthSwitcher: typeof import('./src/components/MonthSwitcher/index.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutCheckbox: typeof import('nutui-uniapp/components/checkbox/checkbox.vue')['default']
    NutCheckboxGroup: typeof import('nutui-uniapp/components/checkboxgroup/checkboxgroup.vue')['default']
    NutConfigProvider: typeof import('nutui-uniapp/components/configprovider/configprovider.vue')['default']
    NutEmpty: typeof import('nutui-uniapp/components/empty/empty.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutInput: typeof import('nutui-uniapp/components/input/input.vue')['default']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['default']
    NutTabPane: typeof import('nutui-uniapp/components/tabpane/tabpane.vue')['default']
    NutTabs: typeof import('nutui-uniapp/components/tabs/tabs.vue')['default']
    NutToast: typeof import('nutui-uniapp/components/toast/toast.vue')['default']
    PageList: typeof import('./src/components/PageList/index.vue')['default']
    Summary: typeof import('./src/components/Summary/index.vue')['default']
    WeappTailwindcss: typeof import('./src/components/WeappTailwindcss.vue')['default']
  }
}
